name: 5glab
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
#  - intel-openmp=2022.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
#  - mkl=2022.0.0
  - numpy=1.22.3
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - python_abi=3.9
  - setuptools=58.0.4
  - sqlite=3.38.0
  - tbb=2021.5.0
  - tzdata=2021e
  - wheel=0.37.1
  - pip:
    - cloudpickle==1.6.0
    - cycler==0.11.0
    - fonttools==4.31.2
    - gym==0.19.0
    - kiwisolver==1.4.0
    - matplotlib==3.5.1
    - numpy==1.22.3
    - packaging==21.3
    - pandas==1.4.1
    - pillow==9.0.1
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytz==2022.1
    - six==1.16.0
    - stable-baselines3==1.4.0
    - tensorboard==2.9.0
    - torch==1.11.0
    - typing-extensions==4.1.1
